language: python
python:
  - 2.6
  - 2.7
branches:
  except:
    - deploy
install:
  - sudo apt-get install git python-dev libpq-dev libldap2-dev libsasl2-dev
  - ln -s buildout.d/development.cfg buildout.cfg
  - python bootstrap.py
  - bin/buildout
  - cp intranet/localsettings.py.example intranet/localsettings.py
  - bin/django syncdb --all --noinput
  - bin/django migrate --fake --noinput
script: bin/test

notifications:
  irc:
    - "irc.sioff.net#kiberpipa"
